export const COUNTRIES: { code: string; name: string }[] = [
  { code: 'ALB', name: 'Albania' },
  { code: 'ALG', name: 'Algeria' },
  { code: 'AND', name: 'Andorra' },
  { code: 'ANG', name: 'Angola' },
  { code: 'ANT', name: 'Antigua & Barbuda' },
  { code: 'ARG', name: 'Argentina' },
  { code: 'ARM', name: 'Armenia' },
  { code: 'AUS', name: 'Australia' },
  { code: 'AUT', name: 'Austria' },
  { code: 'AZE', name: 'Azerbaijan' },
  { code: 'BAH', name: 'Bahamas' },
  { code: 'BRN', name: 'Bahrain' },
  { code: 'BAN', name: 'Bangladesh' },
  { code: 'BAR', name: 'Barbados' },
  { code: 'BEL', name: 'Belgium' },
  { code: 'BIZ', name: 'Belize' },
  { code: 'BOL', name: 'Bolivia' },
  { code: 'BIH', name: 'Bosnia and Herzegovina' },
  { code: 'BOT', name: 'Botswana' },
  { code: 'BRA', name: 'Brazil' },
  { code: 'BUL', name: 'Bulgaria' },
  { code: 'BDI', name: 'Burundi' },
  { code: 'CAM', name: 'Cambodia' },
  { code: 'CAN', name: 'Canada' },
  { code: 'CAY', name: 'Cayman Islands' },
  { code: 'CHI', name: 'Chile' },
  { code: 'CHN', name: 'China' },
  { code: 'TPE', name: 'Chinese Taipei' },
  { code: 'COL', name: 'Colombia' },
  { code: 'COD', name: 'Congo' },
  { code: 'CRC', name: 'Costa Rica' },
  { code: 'CRO', name: 'Croatia' },
  { code: 'CUB', name: 'Cuba' },
  { code: 'CYP', name: 'Cyprus' },
  { code: 'CZE', name: 'Czech Republic' },
  { code: 'DEN', name: 'Denmark' },
  { code: 'DOM', name: 'Dominican Republic' },
  { code: 'ECU', name: 'Ecuador' },
  { code: 'EGY', name: 'Egypt' },
  { code: 'ESA', name: 'El Salvador' },
  { code: 'ERI', name: 'Eritrea' },
  { code: 'EST', name: 'Estonia' },
  { code: 'ETH', name: 'Ethiopia' },
  { code: 'FIN', name: 'Finland' },
  { code: 'FRA', name: 'France' },
  { code: 'GAB', name: 'Gabon' },
  { code: 'GEO', name: 'Georgia' },
  { code: 'GER', name: 'Germany' },
  { code: 'GRE', name: 'Greece' },
  { code: 'GUA', name: 'Guatemala' },
  { code: 'GUY', name: 'Guyana' },
  { code: 'HAI', name: 'Haiti' },
  { code: 'HON', name: 'Honduras' },
  { code: 'HKG', name: 'Hong Kong, China' },
  { code: 'HUN', name: 'Hungary' },
  { code: 'ISL', name: 'Iceland' },
  { code: 'IND', name: 'India' },
  { code: 'IDN', name: 'Indonesia' },
  { code: 'IRI', name: 'Iran' },
  { code: 'IRQ', name: 'Iraq' },
  { code: 'IRE', name: 'Ireland' },
  { code: 'ISR', name: 'Israel' },
  { code: 'ITA', name: 'Italy' },
  { code: 'CIV', name: 'Ivory Coast' },
  { code: 'JAM', name: 'Jamaica' },
  { code: 'JAP', name: 'Japan' },
  { code: 'JOR', name: 'Jordan' },
  { code: 'KAZ', name: 'Kazakhstan' },
  { code: 'KEN', name: 'Kenya' },
  { code: 'KOS', name: 'Kosovo' },
  { code: 'KUW', name: 'Kuwait' },
  { code: 'KGZ', name: 'Kyrgyzstan' },
  { code: 'LAT', name: 'Latvia' },
  { code: 'LBN', name: 'Lebanon' },
  { code: 'LBA', name: 'Libya' },
  { code: 'LIE', name: 'Liechtenstein' },
  { code: 'LTU', name: 'Lithuania' },
  { code: 'LUX', name: 'Luxembourg' },
  { code: 'MAC', name: 'Macao, China' },
  { code: 'MAD', name: 'Madagascar' },
  { code: 'MAS', name: 'Malaysia' },
  { code: 'MDV', name: 'Maldives' },
  { code: 'MLT', name: 'Malta' },
  { code: 'MTN', name: 'Mauritania' },
  { code: 'MRI', name: 'Mauritius' },
  { code: 'MEX', name: 'Mexico' },
  { code: 'MDA', name: 'Moldova, Republic of' },
  { code: 'MON', name: 'Monaco' },
  { code: 'MGL', name: 'Mongolia' },
  { code: 'MNE', name: 'Montenegro' },
  { code: 'MAR', name: 'Morocco' },
  { code: 'MOZ', name: 'Mozambique' },
  { code: 'NAM', name: 'Namibia' },
  { code: 'NEP', name: 'Nepal' },
  { code: 'NED', name: 'Netherlands' },
  { code: 'NZL', name: 'New Zealand' },
  { code: 'NCA', name: 'Nicaragua' },
  { code: 'NGR', name: 'Nigeria' },
  { code: 'MKD', name: 'North Macedonia' },
  { code: 'NOR', name: 'Norway' },
  { code: 'OMA', name: 'Oman' },
  { code: 'PAK', name: 'Pakistan' },
  { code: 'PLE', name: 'Palestine, State of' },
  { code: 'PAN', name: 'Panama' },
  { code: 'PAR', name: 'Paraguay' },
  { code: 'PER', name: 'Peru' },
  { code: 'PHI', name: 'Philippines' },
  { code: 'POL', name: 'Poland' },
  { code: 'POR', name: 'Portugal' },
  { code: 'PUR', name: 'Puerto Rico' },
  { code: 'QAT', name: 'Qatar' },
  { code: 'ROU', name: 'Romania' },
  { code: 'RWA', name: 'Rwanda' },
  { code: 'SMR', name: 'San Marino' },
  { code: 'KSA', name: 'Saudi Arabia' },
  { code: 'SEN', name: 'Senegal' },
  { code: 'SRB', name: 'Serbia' },
  { code: 'SEY', name: 'Seychelles' },
  { code: 'SGP', name: 'Singapore' },
  { code: 'SVK', name: 'Slovakia' },
  { code: 'SLO', name: 'Slovenia' },
  { code: 'RSA', name: 'South Africa' },
  { code: 'KOR', name: 'South Korea' },
  { code: 'ESP', name: 'Spain' },
  { code: 'SRI', name: 'Sri Lanka' },
  { code: 'SUD', name: 'Sudan' },
  { code: 'SWE', name: 'Sweden' },
  { code: 'SUI', name: 'Switzerland' },
  { code: 'SYR', name: 'Syrian Arab Republic' },
  { code: 'TAN', name: 'Tanzania' },
  { code: 'THA', name: 'Thailand' },
  { code: 'TTO', name: 'Trinidad and Tobago' },
  { code: 'TUN', name: 'Tunisia' },
  { code: 'TUR', name: 'Türkiye' },
  { code: 'TKM', name: 'Turkmenistan' },
  { code: 'UGA', name: 'Uganda' },
  { code: 'UKR', name: 'Ukraine' },
  { code: 'UAE', name: 'United Arab Emirates' },
  { code: 'GBR', name: 'United Kingdom' },
  { code: 'USA', name: 'United States' },
  { code: 'URU', name: 'Uruguay' },
  { code: 'UZB', name: 'Uzbekistan' },
  { code: 'VEN', name: 'Venezuela' },
  { code: 'VIE', name: 'Vietnam' },
  { code: 'YEM', name: 'Yemen' },
  { code: 'ZAM', name: 'Zambia' },
  { code: 'ZIM', name: 'Zimbabwe' },
]

export function countryName(code: string): string {
  return COUNTRIES.find((c) => c.code === code)?.name ?? code
}
